class PlayerService {
    getPlayers = () => {
        return [
            {
                "PERSON_ID": 1630162,
                "FIRST_NAME": "Anthony",
                "LAST_NAME": "Edwards",
                "DISPLAY_FIRST_LAST": "Anthony Edwards",
                "DISPLAY_LAST_COMMA_FIRST": "Edwards, Anthony",
                "DISPLAY_FI_LAST": "A. Edwards",
                "PLAYER_SLUG": "anthony-edwards",
                "BIRTHDATE": "2001-08-05T00:00:00",
                "SCHOOL": "Georgia",
                "COUNTRY": "USA",
                "LAST_AFFILIATION": "Georgia/USA",
                "HEIGHT": "6-4",
                "WEIGHT": "225",
                "SEASON_EXP": 0,
                "JERSEY": "1",
                "POSITION": "Guard",
                "ROSTERSTATUS": "Active",
                "GAMES_PLAYED_CURRENT_SEASON_FLAG": "Y",
                "TEAM_ID": 1610612750,
                "TEAM_NAME": "Timberwolves",
                "TEAM_ABBREVIATION": "MIN",
                "TEAM_CODE": "timberwolves",
                "TEAM_CITY": "Minnesota",
                "PLAYERCODE": "anthony_edwards",
                "FROM_YEAR": 2020,
                "TO_YEAR": 2020,
                "DLEAGUE_FLAG": "N",
                "NBA_FLAG": "Y",
                "GAMES_PLAYED_FLAG": "Y",
                "DRAFT_YEAR": "2020",
                "DRAFT_ROUND": "1",
                "DRAFT_NUMBER": "1",
                "PRIMARY_COLOR": "rgb(12, 35, 64)",
                "SECONDARY_COLOR": "rgb(35, 97, 146)",
                "LINE_COLOR": "#78BE20",
            },
            {
                "PERSON_ID": 1630163,
                "FIRST_NAME": "LaMelo",
                "LAST_NAME": "Ball",
                "DISPLAY_FIRST_LAST": "LaMelo Ball",
                "DISPLAY_LAST_COMMA_FIRST": "Ball, LaMelo",
                "DISPLAY_FI_LAST": "L. Ball",
                "PLAYER_SLUG": "lamelo-ball",
                "BIRTHDATE": "2001-08-22T00:00:00",
                "SCHOOL": "Illawarra",
                "COUNTRY": "USA",
                "LAST_AFFILIATION": "Illawarra/USA",
                "HEIGHT": "6-6",
                "WEIGHT": "180",
                "SEASON_EXP": 0,
                "JERSEY": "2",
                "POSITION": "Guard",
                "ROSTERSTATUS": "Active",
                "GAMES_PLAYED_CURRENT_SEASON_FLAG": "Y",
                "TEAM_ID": 1610612766,
                "TEAM_NAME": "Hornets",
                "TEAM_ABBREVIATION": "CHA",
                "TEAM_CODE": "hornets",
                "TEAM_CITY": "Charlotte",
                "PLAYERCODE": "lamelo_ball",
                "FROM_YEAR": 2020,
                "TO_YEAR": 2020,
                "DLEAGUE_FLAG": "N",
                "NBA_FLAG": "Y",
                "GAMES_PLAYED_FLAG": "Y",
                "DRAFT_YEAR": "2020",
                "DRAFT_ROUND": "1",
                "DRAFT_NUMBER": "3",
                "PRIMARY_COLOR": "rgb(29,17,96)",
                "SECONDARY_COLOR": "rgb(0,120,140)",
                "LINE_COLOR": "#00788C",
            }
        ];
    }
}
 
export default PlayerService;